
ET,6,39 
!*  
R,8,0,0,0.437019372,1036.725576,0.699230996,1244.070691,
RMORE,9.614426189,414.6902303,50,414.6902303,,, 
RMORE,,,,,,,
RMORE,,,,,,,
RMORE,,,,,,,
RMORE,,,,,,,
RMORE,,,,,  
!*  
KEYOPT,6,1,1
KEYOPT,6,2,0
KEYOPT,6,3,3
KEYOPT,6,4,0
KEYOPT,6,6,0
!*  
! create combin39 springZ
TYPE,6
MAT,
REAL,8
*DO,i,1,SpringNode_conc_count
  E,Arr_SpringNode_tendon(i),Arr_SpringNode_conc_sorted(i)
*ENDDO
